name: Lokalize PR check
on:
  pull_request:
    branches:
      - "main"
jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test_file_changes
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: validate-locale
