name: Lokalize PR check
on:
  pull_request:
    branches:
      - "main"
jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        with:
          script: |
            if steps.file_changes.outputs.files.length !== 2 {
              throw new Error("More than 2 files were changed in this lokalize PR");
            }
            throw new Error("I really wanna fail");
