name: Lokalize PR check
on:
  pull_request:
    branches:
      - "main"
jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: cat $HOME/files.json
