name: Lokalize PR check
on:
  pull_request:
    paths:
      - "locale/*.json"
jobs:
  autocheckandapprove:
    runs-on: ubuntu-latest
    steps:
      - name: initialCheck
        if: github.actor != 'VWSCoronaDashboard1' || startsWith(github.head_ref, 'lokalise-') == false
        run: |
          exit 1
      - uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: locale validation
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: validate-locale
      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: lokalise
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ github.token }}
  automerge:
    name: Auto merge after successful checks
    # By default, jobs run in parallel. To run the jobs sequentially, they keywords "needs" is needed.
    # Auto merge action can be done only when the PR is approved, hence this automerge needs autocheckandapprove as a prerequisite
    needs: autocheckandapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.12.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_LABELS: lokalise
          MERGE_METHOD: squash
